language: node_js

stages:
    - compliance-tests
    - security-tests
    - unit-tests
    - quality-tests

matrix:
    fast_finish: true
    allow_failures:
          - script:
              - npm outdated

jobs:
    include:
        - stage: compliance-tests
          script:
              - npx @commitlint/travis-cli

        - stage: compliance-tests
          script:
              - npm run compliance:eslint

        - stage: security-tests
          script:
              - npm outdated

        - stage: security-tests
          script:
              - npm run security:nsp

        - stage: unit-tests
          script:
              - npm run unit:test

        - stage: quality-tests
          script:
              - npm run quality:sonarjs
